services:
    '@enhavo/shop/action/CreateAttributeAction':
        import: 'CreateAttributeAction'
        chunk: 'action'
        arguments:
            - '@enhavo/app/view/View'
            - '@enhavo/core/Router'
            - '@enhavo/app/modal/ModalManager'
            - '@enhavo/core/Translator'
        tags:
            - 'enhavo_app.action'
